# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/clusters_espaciales',
                'doc_host': 'https://andfonseca.github.io',
                'git_url': 'https://github.com/andfonseca/clusters_espaciales',
                'lib_path': 'clusters_espaciales'},
  'syms': {'clusters_espaciales.core': {'clusters_espaciales.core.foo': ('core.html#foo', 'clusters_espaciales/core.py')}}}
